# Generated by Django 2.1.3 on 2019-01-13 07:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('poly', django.contrib.gis.db.models.fields.GeometryField(geography=True, srid=4326)),
                ('population', models.BigIntegerField(null=True)),
                ('area_land', models.BigIntegerField(null=True)),
                ('area_water', models.BigIntegerField(null=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='states.State')),
            ],
        ),
    ]
