# Generated by Django 2.1.3 on 2019-02-05 05:04

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0003_auto_20190119_0642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('move', 'Move'), ('fail', 'Move Failure'), ('weight', 'Weight Update'), ('burn start', 'Begin Burn in'), ('burn end', 'End Burn in'), ('anneal start', 'Begin Linear Simulated Annealing'), ('anneal end', 'End Linear Simulated Annealing')], max_length=13)),
                ('weights', django.contrib.postgres.fields.jsonb.JSONField()),
                ('map', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('scores', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('districts', models.PositiveIntegerField()),
                ('running', models.BooleanField()),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='states.State')),
            ],
        ),
        migrations.RemoveField(
            model_name='seedredistrictmap',
            name='state',
        ),
        migrations.DeleteModel(
            name='SeedRedistrictMap',
        ),
        migrations.AddField(
            model_name='event',
            name='run',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='states.Run'),
        ),
    ]
