# Generated by Django 2.1.3 on 2018-11-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0004_statesubsection_population'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statesubsection',
            name='population',
            field=models.BigIntegerField(null=True),
        ),
    ]
