# Generated by Django 2.1.3 on 2019-02-05 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0004_auto_20190205_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('move', 'Move'), ('fail', 'Move Failure'), ('weight', 'Weight Update'), ('burn end', 'End Burn in'), ('anneal start', 'Begin Linear Simulated Annealing'), ('anneal end', 'End Linear Simulated Annealing')], max_length=13),
        ),
    ]
