# Generated by Django 2.1.3 on 2018-11-29 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0005_auto_20181129_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='redistrcting',
            name='multi_polygon_behavior',
            field=models.CharField(choices=[('accept', 'Treat Multipolygons as polygons'), ('tear', 'Break apart Multipolygons and combine them again post simulation'), ('convexhull', 'Clump all polygons that are in the convex hull of a multipolygon')], default='accept', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seedredistrictmap',
            name='districts',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seedredistrictmap',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state',
            name='graph_representation',
            field=models.FileField(null=True, upload_to='state/nx/'),
        ),
        migrations.AlterField(
            model_name='redistrcting',
            name='shape_file',
            field=models.FileField(upload_to='redist/shp/'),
        ),
        migrations.AlterField(
            model_name='redistrcting',
            name='visualization',
            field=models.ImageField(upload_to='redist/img/'),
        ),
        migrations.AlterField(
            model_name='seedredistrictmap',
            name='initial_file',
            field=models.FileField(null=True, upload_to='redist/shp/'),
        ),
        migrations.AlterField(
            model_name='seedredistrictmap',
            name='initial_visualization',
            field=models.ImageField(null=True, upload_to='redist/img/'),
        ),
        migrations.AlterField(
            model_name='state',
            name='block_dictionary',
            field=models.FileField(null=True, upload_to='state/map/pop/'),
        ),
        migrations.AlterField(
            model_name='state',
            name='block_shape_file',
            field=models.FileField(null=True, upload_to='state/shp/bg/'),
        ),
        migrations.AlterField(
            model_name='state',
            name='fast_visualization',
            field=models.ImageField(null=True, upload_to='state/img/'),
        ),
        migrations.AlterField(
            model_name='state',
            name='voting_shape_file',
            field=models.FileField(null=True, upload_to='state/shp/vtd/'),
        ),
    ]
