# Generated by Django 2.1.3 on 2018-12-01 00:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0006_auto_20181129_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redistricting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('queue_index', models.IntegerField(default=1, editable=False)),
                ('multi_polygon_behavior', models.CharField(choices=[('accept', 'Treat Multipolygons as polygons'), ('tear', 'Break apart Multipolygons and combine them again post simulation'), ('convexhull', 'Clump all polygons that are in the convex hull of a multipolygon')], max_length=10)),
                ('visualization', models.ImageField(null=True, upload_to='redist/img/')),
                ('graph', models.FileField(null=True, upload_to='redist/nx/')),
                ('shape_file', models.FileField(null=True, upload_to='redist/shp/')),
                ('matrix_map', models.FileField(null=True, upload_to='redist/txt/')),
                ('steps', models.IntegerField(default=0)),
                ('total_runtime', models.FloatField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='redistrcting',
            name='initial',
        ),
        migrations.AddField(
            model_name='seedredistrictmap',
            name='matrix_map',
            field=models.FileField(null=True, upload_to='redist/txt/'),
        ),
        migrations.AddField(
            model_name='seedredistrictmap',
            name='multi_polygon_behavior',
            field=models.CharField(choices=[('accept', 'Treat Multipolygons as polygons'), ('tear', 'Break apart Multipolygons and combine them again post simulation'), ('convexhull', 'Clump all polygons that are in the convex hull of a multipolygon')], default='accept', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seedredistrictmap',
            name='nonprecinct_behavior',
            field=models.CharField(choices=[('predrop', 'Drop the non-precincts before creating an adjacency graph'), ('postdrop', 'Drop the non-precincts after creating an adjacency graph and bridge the gaps'), ('ignore', 'Treat non-precinct polygons like precinct polygons')], default='ignore', max_length=8),
        ),
        migrations.AddField(
            model_name='seedredistrictmap',
            name='shape',
            field=models.FileField(null=True, upload_to='redist/shp/'),
        ),
        migrations.AddField(
            model_name='seedredistrictmap',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('queued', 'Queued'), ('seeding', 'Building Seed Map'), ('running', "Running Weifan's code"), ('visualizing', "Visualization via Zack's code"), ('statistic', "Statistical tests via Langley's code")], default='idle', max_length=11),
        ),
        migrations.AlterField(
            model_name='seedredistrictmap',
            name='initial_file',
            field=models.FileField(null=True, upload_to='redist/nx/'),
        ),
        migrations.DeleteModel(
            name='Redistrcting',
        ),
        migrations.AddField(
            model_name='redistricting',
            name='initial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='states.SeedRedistrictMap'),
        ),
    ]
