# Generated by Django 2.1.3 on 2018-12-03 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0007_auto_20181201_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='seedredistrictmap',
            name='current_step',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='seedredistrictmap',
            name='total_steps',
            field=models.BigIntegerField(null=True),
        ),
    ]
