# Generated by Django 2.1.3 on 2018-12-03 21:19

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0008_auto_20181203_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='censusblock',
            name='poly',
            field=django.contrib.gis.db.models.fields.GeometryField(geography=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='censusblock',
            name='id',
            field=models.CharField(help_text='id', max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='redistricting',
            name='queue_index',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
