# Generated by Django 2.1.3 on 2018-11-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0002_auto_20181129_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='censusblock',
            name='id',
            field=models.BigIntegerField(help_text='id', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='statesubsection',
            name='land_mass',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='statesubsection',
            name='water_mass',
            field=models.BigIntegerField(),
        ),
    ]
