# Generated by Django 2.1.3 on 2018-11-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0003_auto_20181129_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='statesubsection',
            name='population',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
